config/routes.rb
Rails.application.routes.draw do

  resources :matches
  resources :teams

  get 'team/new'

  get 'team/create'

  resources :users

  controller :sessions do
      get 'login' => :new
      post 'login' => :create
      delete 'logout' => :destroy
  end

  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'home#homepage'
  get '', to: 'home#homepage', as: 'home'

  get 'help', to: 'home#help', as: 'help'

  get 'sessions/new'
  get 'sessions/create'
  get 'sessions/destroy'
  get 'users/profile', to: 'users#profile', as: 'profile'
  post 'add_team', to: 'users#add_team', as: 'add_team'
  post 'remove_team1', to: 'users#remove_team1', as: 'remove_team1'
  post 'remove_team2', to: 'users#remove_team2', as: 'remove_team2'
  post 'elimina_team', to: 'teams#elimina_team', as: 'elimina_team'
  post 'choose_team', to: 'matches#choose_team', as: 'choose_team'
  post 'select_team', to: 'matches#select_team', as: 'select_team'
  get 'seleziona_team', to: 'matches#seleziona_team', as: 'seleziona_team'
  post 'select_team2', to: 'matches#select_team2', as: 'select_team2'
  post 'show_match', to: 'matches#show_match', as: 'show_match'
  post 'elimina_match', to: 'matches#elimina_match', as: 'elimina_match'
  post 'send_request', to: 'teams#send_request', as: 'send_request'
  post 'leave_team', to: 'teams#leave_team', as: 'leave_team'
  post 'refuse_member', to: 'teams#refuse_member', as: 'refuse_member'
  post 'remove_member', to: 'teams#remove_member', as: 'remove_member'
  post 'accept_member', to: 'teams#accept_member', as: 'accept_member'
  post 'form2', to: 'teams#form2', as: 'form2'

  post 'new_event', to: 'matches#new_event', as: 'new_event'

  post 'searchtm', to: 'users#searchtm', as: 'searchtm'
  get 'search', to: 'users#search', as: 'search'
end

app/models/match.rb
class Match < ApplicationRecord
end

app/controllers/matches_controller.rb
class MatchesController < ApplicationController
  before_action :set_match, only: [:show, :edit, :update, :destroy]

  def flash_class(level)
    case level
        when :notice then "alert alert-info"
        when :success then "alert alert-success"
        when :error then "alert alert-error"
        when :alert then "alert alert-error"
    end
end

  # GET /matches
  # GET /matches.json
  def index
    @matches = Match.all
  end

  # GET /matches/1
  # GET /matches/1.json
  def show
  end

  def show_match
    idmatch=params['idmatch']

    redirect_to Match.find(idmatch)
  end


  # GET /matches/new
  def new
    @match = Match.new
  end

  # GET /matches/1/edit
  def edit
  end

  # POST /matches
  # POST /matches.json
  def create
    @match = Match.new(match_params)
    if @match[:date] < Date.today or (@match[:date] == Date.today and @match[:time].to_formatted_s(:time) <= Time.now.to_formatted_s(:time))
      flash[:error]="Data non valida"
      redirect_to new_match_path

    else

      respond_to do |format|
        if @match.save
          format.html { redirect_to @match, notice: 'Match was successfully created.' }
          format.json { render :show, status: :created, location: @match }
        else
          format.html { render :new }
          format.json { render json: @match.errors, status: :unprocessable_entity }
        end
      end
    end
  end

  # PATCH/PUT /matches/1
  # PATCH/PUT /matches/1.json
  def update
    respond_to do |format|
      if @match.update(match_params)
        format.html { redirect_to @match, notice: 'Match was successfully updated.' }
        format.json { render :show, status: :ok, location: @match }
      else
        format.html { render :edit }
        format.json { render json: @match.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /matches/1
  # DELETE /matches/1.json
  def destroy
    @match.destroy
    respond_to do |format|
      format.html { redirect_to matches_url, notice: 'Match was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def choose_team
    id=params['id']
    flash[:success]="Choosen team"
    flash[:success]=Team.find(id).name

  end

  def seleziona_team
  end



  def new_event
    idmatch=params['idmatch']
    @match=Match.find(idmatch)
    
    service = Google::Apis::CalendarV3::CalendarService.new
    service.client_options.application_name = "WantedMatch"
    service.authorization = current_user.oauth_token

    cal = service.get_calendar('primary')

    team = Team.find(@match.team1)
    
    event = Google::Apis::CalendarV3::Event.new({
      start: Google::Apis::CalendarV3::EventDateTime.new(date: @match.date),
      end: Google::Apis::CalendarV3::EventDateTime.new(date: @match.date + 1),
      summary: ('Match organized by ' + team.name)
    })

    service.insert_event(cal.id, event)

    redirect_to ("https://calendar.google.com/calendar/r/week/" + @match.date.strftime("%Y/%m/%d"))

  end

  def select_team
    idmatch=params['idmatch']
    idteam=params['idteam']
    @match=Match.find(idmatch)

    Team.find(@match.team1).members.each do |e1|
      Team.find(idteam).members.each do |e2|
        if e1==e2
          $idm=idmatch
          $idt=idteam
          redirect_to seleziona_team_path
          return
        end
      end
    end
    @match[:team2]=idteam
    @match.save

    #aggiungere google calendar

     redirect_to User.find(session[:user_id])
     flash[:success]="Trovata squadra sfidante!"
  end

  def select_team2
    idmatch=params['idmatch']
    idteam=params['idteam']
    @match=Match.find(idmatch)
    @match[:team2]=idteam
    @match.save
    redirect_to User.find(session[:user_id])
    flash[:success]="Trovata squadra sfidante!"
    #aggiungere google calendar
  end


  def elimina_match
    idmatch=params['idmatch']
    Match.find(idmatch).destroy
    redirect_to User.find(session[:user_id])
  end



  private
    # Use callbacks to share common setup or constraints between actions.
    def set_match
      @match = Match.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def match_params
      params.require(:match).permit(:location, :time, :tipo, :date, :team1, :team2)
    end
end

app/helpers/matches_helper.rb
module MatchesHelper
end

app/views/matches/_form.html.erb
<div class="container">
  <div  align="center">
  <% flash.each do |key, value| %>
      <div class="isa_error" style="border-left-style: solid; border-right-style: solid; border-color: #E52B50;">
        <b style="margin-left: -20px;">→ <%= value %></b>
      </div>
  <% end %>
  </div>
  <div class="container pnl" align="center">
    <br>
  <br>
  <br>
  <div class="popup" onclick="popup()"><button class="pic-btn"> Scegli Team </button>
    <span class="popuptext" id="myPopup"><i>Questi sono i tuoi Teams!</i>

      <table>
        <% Team.all.each do |element| %>
          <h3 style="margin-top: 9px;margin-bottom: 9px;">
          <% if User.find(session[:user_id])[:usname]==element[:captain] %>
          <div class="scatola" align="left">

            <tr><div style="font-size: 25px; position:absolute; left: 10px;"><%= element[:name] %></div><%= link_to 'Show', Team.find(element.id), class: 'btn btn-default', style: 'background-color: blue;  color: white; position: absolute; right: 103px; margin-top: -5px; height: 30px; padding: 1px; width: 90px;'%>

              <%= button_tag 'Choose', onclick: 'choose_team(' + element[:id].to_s + ')', class: 'btn btn-choose', style: 'position: absolute; right: 3px; margin-top: -5px; color: white; border-radius: 20px; height: 30px; padding: 1px; width: 90px;' %>
            </tr><br>
          </div>
          <% end %>

          </h3>
        <% end %>
      </table>

    </span>
  </div>
  <label id="mess"> </label><br>

<div align="center">
<%= form_with(model: match, local: true) do |form| %>
  <% if match.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(match.errors.count, "error") %> prohibited this match from being saved:</h2>

      <ul>
      <% match.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <%= form.text_field :team1, id: :match_team1, class: 'hidden'%>
    <div class="field" align="left" style="width: 150px;">
      <p>
        <b style="margin-left: -100px; font-size: 16px;">
          Tipo di partita:
        </b>
      </p>

        <%= form.radio_button :tipo, 'calcio a 5' %><i style="font-size: 18px; margin-left: 15px;">Calcio a 5</i><br><br>
        <%= form.radio_button :tipo, 'calcio a 7' %><i style="font-size: 18px; margin-left: 15px;">Calcio a 7</i><br><br>
        <%= form.radio_button :tipo, 'calcio a 8' %><i style="font-size: 18px; margin-left: 15px;">Calcio a 8</i><br><br>
        <%= form.radio_button :tipo, 'calcio a 11' %><i style="font-size: 18px; margin-left: 15px;">Calcio a 11</i><br><br>
      </div><br><hr>

  <div class="field">
    <p>
      <b style="margin-left: -200px; font-size: 16px;">
        Dove si terrà la partita?
      </b>
    </p>
    <%= form.text_field :location, id: :match_location, class: 'form-ctrl', placeholder: 'Location' %>
  </div><br><hr>

  <div class="field" align="center">
    <p>
      <b style="margin-left: -200px; font-size: 16px;">
        Ora:
      </b>
    </p>    <input id="match_time" name='match[time]' type="time" class="form-control" style="width: 12%;"/>
  </div><br><hr>

  <div class="field">
    <p>
      <b style="margin-left: -200px; font-size: 16px;">
        Data:
      </b>
    </p>    <input id="match_date" name='match[date]' type="date" class="form-control" style="width: 13%;"/>
  </div><br><hr>




  <div class="actions">
    <%= form.submit "Posta Annuncio", :class => 'btn btn-createM', style: 'width: 40%' %>
  </div>
<% end %>
</div>
<br>
<p class="mt-5 mb-3 text-muted text-center"><b style="color: white;">© 2017-2018</b></p>
<hr>
</div>

app/views/matches/edit.html.erb
<h1>Editing Match</h1>

<%= render 'form', match: @match %>

app/views/matches/new.html.erb
<%= render 'form', match: @match %>

app/views/matches/select_team.html.erb
<div style="border: solid 2px; border-color: blue;">
  <br>
  Le due squadre hanno un giocatore in comune... Continuare?<br><br>
  <% link_to "Annulla", roba_path, class: 'btn btn-delete' %>
  <%= form_tag action: 'select_team2', controller: 'matches' do %>
      <%= submit_tag 'Conferma', class: 'btn btn-register'%>
      <%= text_field_tag :idteam, nil, class: 'hidden', value: $idt %>
      <%= text_field_tag :idmatch, nil, class: 'hidden', value: $idm %>
  <% end%>
  <br>
</div>

app/views/matches/select_team2.html.erb
<div style="border: solid 2px; border-color: blue;">
  <br>
  Le due squadre hanno un giocatore in comune... Continuare?<br><br>
  <% link_to "Annulla", Match.find($idm), class: 'btn btn-delete' %>
  <%= form_tag action: 'select_team2', controller: 'matches' do %>
      <%= submit_tag 'Conferma', class: 'btn btn-register'%>
      <%= text_field_tag :idteam, nil, class: 'hidden', value: $idt %>
      <%= text_field_tag :idmatch, nil, class: 'hidden', value: $idm %>
  <% end%>
  <br>
</div>

app/views/matches/seleziona_team.html.erb
<div align="center">
<div style="border: solid 2px; border-color: blue; background-color: gray; opacity: 0.9; width: 30%; margin-top: 60px;">
  <br>
  <p style="font-size: 20px;">Le due squadre hanno un giocatore in comune... Continuare?</p><br><br>
  <%= link_to 'Annulla',  User.find(session[:user_id]), class: 'btn btn-delete', style: 'position: absolute; right: 1090px; top: 236px; color: black;' %>
  <%= form_tag action: 'select_team2', controller: 'matches' do %>
      <%= submit_tag 'Conferma', class: 'btn btn-register',  style: 'margin-left: 120px'%>
      <%= text_field_tag :idteam, nil, class: 'hidden', value: $idt %>
      <%= text_field_tag :idmatch, nil, class: 'hidden', value: $idm %>
  <% end%>
  <br>
</div>
</div>

app/views/matches/show.html.erb
<div class="container" align="center">
<% flash.each do |key, value| %>
    <div class="isa_success" style="border-left-style: solid; border-right-style: solid; border-color: #2E8B57;">
      <b style="margin-left: -20px;">→ <%= value %></b>
    </div>
<% end %>
</div><br>
<div class="container pnl" align="center">
  <br>
  <br>
<br>
<h3 align="center">
<p>
  <strong>Location:</strong>
  <%= @match.location %>
</p>
<br>
<p>
  <strong>Type:</strong>
  <%= @match.tipo %>
</p>
<br>
<p>
  <strong>Time:</strong>
  <%= @match.time.to_formatted_s(:time) %>
</p>
<br>
<p>
  <strong>Date:</strong>
  <%= @match.date %>
</p>
<br>
<p>
  <strong>Team1:</strong>

  <% if Team.find(@match.team1).logo.to_s=="" %>
    <%= image_tag("https://image.freepik.com/icone-gratis/punto-interrogativo_318-52837.jpg", style: 'height: 50px; width: 50px; margin-right: 10px;')%>
  <% else %>
    <%= image_tag(Team.find(@match.team1).logo.to_s, style: 'height: 50px; width: 50px; margin-right: 10px;')%>
  <% end %>


   <%= Team.find(@match.team1)[:name] %>
</p>
<br>
<p>
  <strong>Team2:</strong>
  <% if @match.team2==nil %>
    <b> Cercasi Team sfidante </b><br><br>
  </h3>

    <% if User.find(session[:user_id])[:usname]==Team.find(@match[:team1]).captain %>
    <% else %>




<div align='center'>


    <div class="popup" onclick="popup()"><button class="pic-btn"> Scegli Team </button>
  <span class="popuptext" id="myPopup"><i>Questi sono i tuoi Teams!</i>
    <table>
      <% Team.all.each do |element| %>

        <h3 style="margin-top: 9px;margin-bottom: 9px;">
        <% if User.find(session[:user_id])[:usname]==element[:captain] %>
        <div class="scatola" align="left">
          <tr><div style="font-size: 25px; position:absolute; left: 10px; "><%= element[:name] %></div><%= link_to 'Show', Team.find(element.id), class: 'btn btn-default', style: 'background-color: blue;  color: white; position: absolute; right: 103px; margin-top: -5px; height: 30px; padding: 1px; width: 90px;'%>
            <%= form_tag action: 'select_team', controller: 'matches' do %>
            		<%= submit_tag 'Choose', class: 'btn btn-choose', style: 'position: absolute; right: 3px; margin-top: -5px; color: white; border-radius: 20px; height: 30px; padding: 1px; width: 90px;' %>
                <%= text_field_tag :idteam, nil, class: 'hidden', value: element.id %>
                <%= text_field_tag :idmatch, nil, class: 'hidden', value: @match.id %>

            <% end %>

          </tr><br>
        </div>
        <% end %>

        </h3>
      <% end %>
    </table>
    </div>

    <br><br>
    <% if User.find(session[:user_id])[:oauth_token]==nil %>
      <p>You must be signed with Google to add the event to Calendar</p>
    <% else %>
      <%= form_tag new_event_url do %>
        <%= submit_tag 'Add to Google Calendar', :class => 'btn', :formtarget => "_blank" %>
        <%= text_field_tag :idmatch, nil, class: 'hidden', value: @match.id %>
      <% end %>
    <% end %>

  </span>
  </div>
  <% end %>



  <h3 align="center">

  <% if User.find(session[:user_id]).usname==Team.find(@match[:team1])[:captain] %>
    <%= form_tag action: 'elimina_match', controller: 'matches' do %>
    		<%= submit_tag 'Elimina', class: 'btn btn-default', style: 'background-color: red; margin-left: 10px; color: white;'%> <%= text_field_tag :idmatch, nil, class: 'hidden', value: @match.id %>  <!-- CERCA UTENTI -->
    <% end %>
  <% end %>

  <% else %>
    <%= image_tag(Team.find(@match.team2).logo.to_s, style: 'height: 50px; width: 50px; margin-right: 10px;')%> <%= Team.find(@match.team2)[:name] %>
  <% end %>
</p>
<br>
</h3>
<br>
<p class="mt-5 mb-3 text-muted text-center"><b style="color: white;">© 2017-2018</b></p>
<hr>
</div>