config/routes.rb
Rails.application.routes.draw do

  resources :matches
  resources :teams

  get 'team/new'

  get 'team/create'

  resources :users

  controller :sessions do
      get 'login' => :new
      post 'login' => :create
      delete 'logout' => :destroy
  end

  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'home#homepage'
  get '', to: 'home#homepage', as: 'home'

  get 'help', to: 'home#help', as: 'help'

  get 'sessions/new'
  get 'sessions/create'
  get 'sessions/destroy'
  get 'users/profile', to: 'users#profile', as: 'profile'
  post 'add_team', to: 'users#add_team', as: 'add_team'
  post 'remove_team1', to: 'users#remove_team1', as: 'remove_team1'
  post 'remove_team2', to: 'users#remove_team2', as: 'remove_team2'
  post 'elimina_team', to: 'teams#elimina_team', as: 'elimina_team'
  post 'choose_team', to: 'matches#choose_team', as: 'choose_team'
  post 'select_team', to: 'matches#select_team', as: 'select_team'
  get 'seleziona_team', to: 'matches#seleziona_team', as: 'seleziona_team'
  post 'select_team2', to: 'matches#select_team2', as: 'select_team2'
  post 'show_match', to: 'matches#show_match', as: 'show_match'
  post 'elimina_match', to: 'matches#elimina_match', as: 'elimina_match'
  post 'send_request', to: 'teams#send_request', as: 'send_request'
  post 'leave_team', to: 'teams#leave_team', as: 'leave_team'
  post 'refuse_member', to: 'teams#refuse_member', as: 'refuse_member'
  post 'remove_member', to: 'teams#remove_member', as: 'remove_member'
  post 'accept_member', to: 'teams#accept_member', as: 'accept_member'
  post 'form2', to: 'teams#form2', as: 'form2'

  post 'new_event', to: 'matches#new_event', as: 'new_event'

  post 'searchtm', to: 'users#searchtm', as: 'searchtm'
  get 'search', to: 'users#search', as: 'search'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WantedMatch</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'https://stackpath.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css' %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <nav class="navbar navbar-expand-md navbar-dark bg-dark" style="position: absolute; top: 0px; left: 0px; width: 100%">
      <%= link_to "WantedMatch",  home_path , :class => "navbar-brand" %>
      <div class="collapse navbar-collapse" id="navbarCollapse">
        <ul class="nav navbar-nav">
          <li>
            <%= link_to "Profile", if session[:user_id]; user_url(session[:user_id]); end , :class => 'btn btn-default', :style => 'color: gray' %> <!-- user_url(session[:user_id]) -->
          </li>
        </ul>
      </div>


      <!-- barra di ricerca -->
      <div class="search-bar">

        <%= form_tag action: 'searchtm', controller: 'users' do %>
          <%= text_field_tag :campo, nil, class: 'barra', placeholder: '  Search Teams and Matches...' %>
          <%= submit_tag "", class: 'search-button' %>
        <% end %>

      </div>

      <div class="collapse navbar-collapse" id="navbarCollapse" style="position: absolute; right: 12px; bottom: 2px;">
        <div class="dropdown" style="margin-right: 30%;"> <!--TEAM-->
  		  	 <li>
            <%= link_to "=", '#', :class => 'btn btn-default dropbtn link', :style => 'color: gray' %>
          </li>
  			    <div class="dropdown-content" id="ddc">
              <%= link_to "Login", login_url %>
              <%= link_to "Logout", sessions_destroy_path %>
              <%= link_to "Create Team", new_team_path %>
              <%= link_to "Create Match", new_match_path %>
              <%= link_to "Help", help_path %>
            </div>
			   </div>
      </div>

    </nav>
    <div style= 'margin-top: 50px;'>
      <br>
      <br>

        <%= yield %>

    </div>
  </body>
</html>